version: '3.2'

services:
  postgresql:
    image: arm32v6/postgres:10.1-alpine
    volumes:
    - 'pgsql-data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_USER=freshrss
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=freshrss
    networks:
      - freshrss_nw
      - default
    deploy:
      mode: global
      placement:
        constraints: [node.labels.node_name == worker01]
        
  freshrss:
    image: jie211/freshrss
    depends_on:
      - postgresql
    networks:
      - freshrss_nw
      - default
    ports:
      - "8001:80"
    volumes:
      - 'freshrss-data:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/20
      - TZ=Asia/Tokyo
    deploy:
        mode: global
        placement:
          constraints: [node.labels.node_name == worker01]

networks:
  freshrss_nw:
    driver: overlay
    attachable: true
volumes:
  pgsql-data:
  freshrss-data:
